server:
  port: 9000

valorant:
  api:
    url: "https://api.pandascore.co/valorant/"
    key: "SsHh29rZals6s5dqJviygQuAOEWW6Q40hsb7zLWGwIJqMkTqdMk"

logging:
  level:
    com.fasterxml.jackson: DEBUG